export const locations = [
  {
    name: "Lisbon",
    country: "Portugal",
    surfing: 8,
    bjj: 7,
    cost: 6,
    healthcare: 9,
    airports: 9,
    activities: ["surfing", "bjj", "cycling", "yoga"],
    vibe: "coastal city with strong expat community",
    bjjGyms: [
      "Gracie Barra Lisbon",
      "Academia BJJ Lisboa",
      "Alliance Jiu Jitsu Lisbon",
    ],
  },
  {
    name: "Porto",
    country: "Portugal",
    surfing: 7,
    bjj: 6,
    cost: 7,
    healthcare: 9,
    airports: 8,
    activities: ["surfing", "cycling", "yoga", "walking"],
    vibe: "laid-back riverside city with relaxed pace",
    bjjGyms: ["Focus Jiu Jitsu Porto", "Invictus BJJ Porto", "Gracie Porto"],
  },
  {
    name: "Barcelona",
    country: "Spain",
    surfing: 7,
    bjj: 7,
    cost: 6,
    healthcare: 9,
    airports: 9,
    activities: ["bjj", "cycling", "yoga", "beach sports"],
    vibe: "vibrant Mediterranean city with active lifestyle",
    bjjGyms: [
      "ZR Team Barcelona",
      "Checkmat Barcelona",
      "Gracie Barra Barcelona",
    ],
  },
  {
    name: "Bangkok",
    country: "Thailand",
    surfing: 5,
    bjj: 8,
    cost: 9,
    healthcare: 7,
    airports: 9,
    activities: ["bjj", "boxing", "yoga", "city fitness"],
    vibe: "fast-paced urban hub with great convenience",
    bjjGyms: [
      "Bangkok Fight Lab",
      "Arete BJJ",
      "Elite Fight Club Bangkok",
    ],
  },
  {
    name: "Phuket",
    country: "Thailand",
    surfing: 8,
    bjj: 7,
    cost: 8,
    healthcare: 7,
    airports: 8,
    activities: ["surfing", "boxing", "yoga", "diving"],
    vibe: "island lifestyle with beach-focused routine",
    bjjGyms: ["Phuket Grappling Academy", "Tiger Muay Thai BJJ", "Sutai BJJ"],
  },
  {
    name: "Mexico City",
    country: "Mexico",
    surfing: 4,
    bjj: 8,
    cost: 8,
    healthcare: 7,
    airports: 9,
    activities: ["bjj", "boxing", "cycling", "yoga"],
    vibe: "big-city energy with strong fitness scene",
    bjjGyms: [
      "Bujutsu Mexico",
      "Renzo Gracie Mexico City",
      "Alliance Mexico City",
    ],
  },
  {
    name: "Tamarindo",
    country: "Costa Rica",
    surfing: 9,
    bjj: 6,
    cost: 6,
    healthcare: 6,
    airports: 6,
    activities: ["surfing", "yoga", "beach running", "boxing"],
    vibe: "small surf town with outdoors-first lifestyle",
    bjjGyms: [
      "Tamarindo BJJ Club",
      "Checkmat Costa Rica",
      "Nosara BJJ Academy",
    ],
  },
];
